# Generated by Django 5.1.5 on 2025-01-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_ad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ad',
            new_name='Listing',
        ),
    ]
